<a href="https://colab.research.google.com/github/tisRobin/Recommender_System/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The Dataset

https://osf.io/3uw9d/

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
participant = pd.read_csv('/content/gdrive/MyDrive/Group 3/Data/K-pop songs Dataset/Data 1 - raw-participant.csv',  encoding='cp949')

In [ ]:
participant = participant[participant['song_country'] == 'KR']
participant

,rater_nationality,participant_id,stimID,repeated_trial,song_country,song_year,singer_gender,preference_5pt,familiarity_4pt,calm,tense,cheerful,sad,danceable,love,dreamy,electronic,energy
0,American,participant_US1,KR-2014-block11,f,KR,2014,m,4,1,1,1,4,1,4,4,4,4,4
1,American,participant_US1,KR-2013-block11,f,KR,2013,f,1,1,2,1,4,1,4,4,2,3,4
5,American,participant_US1,KR-2012-block11,f,KR,2012,f,5,1,2,1,2,2,3,4,4,2,3
7,American,participant_US3,KR-2018-block11,f,KR,2018,m,2,1,2,2,1,3,1,2,2,1,2
10,American,participant_US3,KR-2015-block11,f,KR,2015,m,3,1,1,1,3,1,2,2,2,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11490,Brazilian,participant_BR6,KR-2013-block5,f,KR,2013,m,2,1,2,1,2,1,2,1,1,2,2
11491,Brazilian,participant_BR6,KR-2015-block5,f,KR,2015,f,3,1,2,1,2,1,3,3,2,2,2
11492,Brazilian,participant_BR6,KR-2011-block5,f,KR,2011,f,1,1,2,3,1,3,1,1,1,1,1
11494,Brazilian,participant_BR6,KR-2017-block5,f,KR,2017,f,3,1,2,1,2,1,2,1,2,2,2
11499,Brazilian,participant_BR6,KR-2019-block5,f,KR,2019,f,2,1,2,1,1,1,2,1,1,2,2

In [ ]:
KR_song = pd.read_csv('/content/gdrive/MyDrive/Group 3/Data/K-pop songs Dataset/Data 2 - song_chart.csv',  encoding = 'utf-8')

In [ ]:
KR_song

,song_origin,chart_source,year,stimID,song_query,artist_query,song_result_spotify,artist_result_spotify,spotify_trackid,preview.url,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,KOR,Gaon Chart,2010,KR-2010-block1,Here I Am,"포맨 (4men), 美",Here I am,4MEN,2HeHipLSY7SWKLjsZdUbjQ,https://p.scdn.co/mp3-preview/8e5d94375aa154f3...,...,-7.834,1,0.0335,0.8540,0.000000,0.1030,0.101,129.552,235563,4
1,KOR,Gaon Chart,2010,KR-2010-block2,밤하늘의 별을..,"양정승 (kiroy Y), Kcm & No Noo",밤하늘의 별을..,Kiroy Y,3zNyjuCpWig3iYWs9PgbDM,https://p.scdn.co/mp3-preview/0a34821c26bbafb2...,...,-4.578,1,0.0609,0.2410,0.000001,0.1160,0.406,153.807,225787,4
2,KOR,Gaon Chart,2010,KR-2010-block3,Y,엠블랙 (mblaq),Y,MBLAQ,3xVGwwax3gAPAkJewnB2eZ,https://p.scdn.co/mp3-preview/c9e9462cf7b31162...,...,-4.828,0,0.1420,0.0298,0.000004,0.0967,0.875,122.952,208523,4
3,KOR,Gaon Chart,2010,KR-2010-block4,사랑한다는 말,남규리,사랑한다는 말,Nam Gyu ri,1o68HIqheZWvKk4m9DnCK0,https://p.scdn.co/mp3-preview/e0a64b47cc65954b...,...,-7.516,1,0.0372,0.8130,0.000000,0.1110,0.172,134.063,248099,4
4,KOR,Gaon Chart,2010,KR-2010-block5,"사랑, 우정 그리고… (with No Noo & 양정승)",제이비 (jb),"사랑, 우정 그리고…",JB,2ovX90glSOm2ouAIhtV3gB,https://p.scdn.co/mp3-preview/836553176e549f53...,...,-6.121,1,0.0336,0.8170,0.000000,0.1090,0.499,171.757,218906,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,BRA,Crowley,2019,BR-2019-block8,Saudade Infinita,Roberta Miranda,Saudade Infinita,Roberta Miranda,6J2ySKkqPkB0oB2IaqYO1e,https://p.scdn.co/mp3-preview/e96bd3f00838fbf2...,...,-6.369,1,0.0274,0.2240,0.000000,0.1250,0.582,105.960,194893,4
356,BRA,Crowley,2019,BR-2019-block9,Combate,Um44k,Combate,UM44K,2gV8yu7sEnewmsVa4CnbOG,https://p.scdn.co/mp3-preview/76335d9d17acdd5e...,...,-6.116,1,0.1450,0.3150,0.000000,0.0974,0.831,88.040,179253,4
357,BRA,Crowley,2019,BR-2019-block10,Salvou Meu Dia,Mc Kevinho Part.Gusttavo Lima,Salvou meu dia (Participação especial de Gustt...,"MC Kevinho, Gusttavo Lima",7CBImG41isOs2r7lQU7CCy,https://p.scdn.co/mp3-preview/cbcc7edf512a1508...,...,-2.688,0,0.0807,0.4090,0.000000,0.3260,0.830,162.077,163666,4
358,BRA,Crowley,2019,BR-2019-block11,500 Metros,Paula Mattos Part.Lucas Lucco,500 metros (Participação especial de Lucas Lucco),"Paula Mattos, Lucas Lucco",2mo6GXEG5IwAA8CfBViGAf,https://p.scdn.co/mp3-preview/55f5b6b3309ab5ec...,...,-3.862,1,0.0510,0.6190,0.000000,0.1060,0.686,123.872,175326,4
359,BRA,Crowley,2019,BR-2019-block12,Toquin Do Violao,Sandro Cesar,Toquin do Violão,Sandro César,1qrrjgSAnpuw8Pf2NTr5eN,https://p.scdn.co/mp3-preview/f9c44e7fd9407fa1...,...,-3.283,1,0.0699,0.3630,0.000000,0.0928,0.735,147.880,167211,4

In [ ]:
song_pref = pd.merge(participant, KR_song, how = 'left', on = 'stimID')

In [ ]:
song_pref.columns

Index(['rater_nationality', 'participant_id', 'stimID', 'repeated_trial',
       'song_country', 'song_year', 'singer_gender', 'preference_5pt',
       'familiarity_4pt', 'calm', 'tense', 'cheerful', 'sad', 'danceable',
       'love', 'dreamy', 'electronic', 'energy_x', 'song_origin',
       'chart_source', 'year', 'song_query', 'artist_query',
       'song_result_spotify', 'artist_result_spotify', 'spotify_trackid',
       'preview.url', 'ISRC', 'danceability', 'energy_y', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [ ]:
ratings = song_pref[["participant_id", "song_query", "preference_5pt"]]
ratings

       participant_id         song_query  preference_5pt
0     participant_US1            Thunder               4
1     participant_US1            그녀의 사무실               1
2     participant_US1                사랑아               5
3     participant_US3                영원히               2
4     participant_US3             너를 그리다               3
...               ...                ...             ...
3840  participant_BR6  만약에 말야 (전우성 Solo)               2
3841  participant_BR6  Wifey (feat. Mc몽)               3
3842  participant_BR6           Break Up               1
3843  participant_BR6             낡은 그리움               3
3844  participant_BR6              Flash               2

[3845 rows x 3 columns]

In [ ]:
ratings.to_csv('/content/gdrive/MyDrive/Group 3/Data/K-pop songs Dataset/Ratings.csv', index = None, header=True )